### ISSUE TITLE
Sample rate - plot view and acquiring

### ISSUE THREAD

**Issue by dpizetta** [dpizetta/wavy#3]
There is a problem with our sample rate. When we change it, the sample rate (timer) of the plot is changed and the sample rate for acquiring data (audio sample rate) is changed too. Sample rate less then 10 Hz is not compatible with the sound board. The range, simplified, is from 1kHz to 40kHz. 

My suggestion is to use unchangeable value for the plot's sample rate (slowest one) and we just change the sample rate for acquisition (that determines how big would be the file - number of points).

I don't know if any value is possible between the range I said, if not, we need to put a selection input with static values.

**Comment by dpizetta** [comment]
I realized that we don't need to change the sample rate from acquiring neither make some down sample over data. We are using the export function from pyqtgraph, the the data are actually under downsample as we determine this property in the graph. So when we export the data, data are converted. 

We need just calculate the maximum and minimum values for sample rate to put on GUI. We keep the acquiring sample rate in 44kHz as you mentioned that is the best value.

**Comment by dpizetta** [comment]
Here is the link about it: http://www.pyqtgraph.org/documentation/graphicsItems/plotdataitem.html

Look for Downsample

**Comment by Wa59** [comment]
I did some testing and those values are really dependent on the soundcard used. I forced pyaudio to use the recording sample rate that was set in the OS sound config. The chunk size starts to throw input overflows when below ~ 512 using DirectInput , ~ 430 using WDM (those are about a 0.01s sample interval, I left that as the minimum for now, maybe we will need to use a larger one to prevent input overflows on slower soundcards) or ~ 60 using ASIO or Jack. (Not supported by most cards).

I was reading about this and maybe we can lower the sample interval if we increase the latency of the real time capture of audio, but pyaudio doesn't seem to allow us to do that. I think that even a 0.05s sample interval would be more than enough for our needs, but we can test that later.

**Comment by dpizetta** [comment]
Ok, but I think we will need synchronized threads to do the correct work. 
![2015-05-27 10 29 40](https://cloud.githubusercontent.com/assets/5084939/7837112/86915f4c-045b-11e5-8328-ab47cf6e4b88.jpg)

CHUNCK = 1024
RATE = 44100
frames = []

while program_is_opened:
# this reads for a sample interval
for i in range(0, int(RATE / CHUNK \* SAMPLE_INTERVAL)):
    data = stream.read(CHUNK)
    frames.append(data)
# copy to buffer - lock here
buffer = frames
# send a signal to real time window to read buffer
SAMPLE_READY.emit()
# reads the buffer and clean it - unlock after here
---------------------------------------------------
# if it's recording, copy the data to recording plot

There is no timer in the plots, it receives the signal to be updated.

**Comment by dpizetta** [comment]
But we should change those things after the class that we need to use it. Could you test the program on Thursday or Friday this week in the lab? Just to check the timing for acquisition?

PS: After your changes, in my laptop it's working fine, the time is ok.

**Comment by dpizetta** [comment]
Close for now. We should work in another version using threads.
