### ISSUE TITLE
Auto stop is stopping in the wrong value, actually in a half

### ISSUE THREAD

**Issue by dpizetta** [dpizetta/wavy#6]
I put a print here.

![image](https://cloud.githubusercontent.com/assets/5084939/7800980/efd08b0e-02f3-11e5-8ee7-48846db9858e.png)

**Comment by dpizetta** [comment]
See #7

**Comment by Wa59** [comment]
I fixed it for now, but we must find out why the graph slows down when recording. Resizing the graph in real time to the screen width takes too much resources, perhaps?
