### ISSUE TITLE
The acquisition time is half of the amount should be

### ISSUE THREAD

**Issue by dpizetta** [dpizetta/wavy#7]
I've calculated the periods for the curves that we acquired using your software and the Pasco software. Your software is acquiring the half of the amount. Wavy provided t = (0.58 +- 0.07)s and Pasco t = (1.18 +- 0.08)s.

**Comment by dpizetta** [comment]
See #6

**Comment by dpizetta** [comment]
I've tested now, measuring 1 minute with a chronometer and recording data, it only records 25 seconds in the screen. May we need to use threads for each one.

**Comment by Wa59** [comment]
Changing the packet size to 512 seems to fix the problem, should we fix a sample rate (ex.:44100Hz) and only change the sample interval?

**Comment by Wa59** [comment]
Made some changes, we need to test if it works.

**Comment by Wa59** [comment]
Seems to be fixed.
